### ISSUE TITLE
Texinfo problem

### ISSUE THREAD

**Issue by AKuHAK2** [ps2dev/ps2toolchain#15]
Maybe it will be better to disable generating info files at all? And just add one short line in the script: https://github.com/jasonrm/ps2toolchain/commit/49ecbea5306e6c11f3dc041dba46f06760923169
It is not so complicated as providing additional patch file. It also reduces time for compiling toolchain and we dont need to care about texinfo (in fact we can remove it at all)

**Comment by sp193** [comment]
It was originally mentioned here, as you know: https://github.com/ps2dev/ps2toolchain/pull/14
I'm just mentioning the original solution to this problem, just so that other people who are interested in this issue in the future will be able to follow the issue fully.

Do you know what are the effects of disabling the generation of the info files? Although I've been using Linux for a long time already, I've never used them and so I don't know what we will be missing. :(
I do know, however, that any solution to this issue will likely be a hack, given that our tools are too old.
